services:
  - type: web
    name: reed-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python downloader.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false 