services:
  - type: web
    name: reed-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn downloader:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /opt/render/project/src 